### ISSUE TITLE
Maxime Technical Specifications issues

### ISSUE THREAD

**Issue by Fus1onAxel** [algosup/2024-2025-project-1-fpga-team-6#2]
I) 2) link not working
<Functional Specifications.> 

II) 4) B) Enemy Collisions Behaviors 

B instead of C  

II) 1) A) PMOD connector
< Board schematics can be found in appendix [here]. > 
no link

III) 2) A) link not working  
< Details of the graphics are provided in the [Functional Specifications].>

**Comment by Carbon-404** [comment]
Corrected with commits:
f4d83c4a680668c32847efdb2381733b8c75af31
2f976b7912560ccdf4757a6fe289dc020a0f71e7
c00e8f0b79874411cd7cd7348fe9aebc6c70aab4
a1960bcc5b5b224eed5903df91af792fa942bdc5
