### ISSUE TITLE
technicalSpecifications graph issues

### ISSUE THREAD

**Issue by Fus1onAxel** [algosup/2024-2025-project-1-fpga-team-6#5]
We can update [this graph](https://github.com/algosup/2024-2025-project-1-fpga-team-6/blob/documents/Documents/TechnicalSpecifications/technicalSpecifications.md#-enemies-movements) by adding an arrow like the red one in this example : 

![arrow in graph](https://github.com/user-attachments/assets/5392ef78-36a8-4728-9740-978021dbd250)

We can update [this graph](https://github.com/algosup/2024-2025-project-1-fpga-team-6/blob/documents/Documents/TechnicalSpecifications/technicalSpecifications.md#b-leveling-system) by replacing the "Do nothing" box by a "Update Level Display" box

![upadate lvl display](https://github.com/user-attachments/assets/e4af3dc4-ca1c-4a63-897f-d120c59cd252)

**Comment by Carbon-404** [comment]
Corrected with commit 49189a590538b9daa994d898327e153bae119a19
